build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Droid Terminal"
  org.opencontainers.image.description: "Terminal interface for Factory's Droid CLI"
  org.opencontainers.image.source: "https://github.com/factory-ai/droid"
  org.opencontainers.image.licenses: "MIT"
