---
name: "Droid Terminal"
description: "Terminal interface for Factory's Droid CLI with persistent auth"
version: "1.0.5"
slug: "droid_terminal"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64
  - armv7

# External resources
url: "https://github.com/factory-ai/droid"

# Web interface configuration
ingress: true
ingress_port: 7682
panel_icon: mdi:robot-industrial
panel_title: "Droid Terminal"
panel_admin: true

# Port configuration
ports:
  7682/tcp: 7682
ports_description:
  7682/tcp: "Web terminal (not required for ingress)"

# Add-on configuration options
options:
  auto_launch_droid:
    name: "Auto-launch Droid"
    description: "Auto-start Droid on terminal open (disable for session picker)"
schema:
  auto_launch_droid: bool?

# Volume mappings for file access
map:
  - config:rw    # Access to Home Assistant configuration files

# API access for Home Assistant integration
hassio_api: true
hassio_role: manager
homeassistant_api: true
auth_api: true

# Service startup configuration
startup: services

# Web UI access URL
webui: http://[HOST]:[PORT:7682]/
